### PR TITLE
Update to gradle 8.0

### PR DESCRIPTION
**Pull request by chrissearle**
### Background

Gradle in the existing project 7.3 supports up to java 16 for 

```kotlin
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    }
```

So - we get lots of warnings about targetting 1.8

Updating to 7.6 now allows up to java 19.

We are left with just one warning:

```
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.7.10` that might work differently than in the requested version `1.8.10`.
```

But I see that this is a common issue with the kotlin-dsl plugin and is something they have several github issues on

### CODE REVIEW

**Comment by chrissearle** [comment]
And yes - I know gradle 8 released today - 8.0 and under 24 hours old - feels a _little_ too new :)

**Review by Watercolours — APPROVED** [review]

**Review by EspenSchei — APPROVED** [review]
Nice 💯

**Comment by chrissearle** [comment]
Update coming @EspenSchei  @Watercolours 

Turns out that 7.6 with --no-build-cache shows that the warning on versions came back.

BUT

We tested gradle 8 - and that worked as wanted.

Will update PR with 8 and see if it builds OK on github in this PR :)

**Comment by madsop-nav** [comment]
Tildelte https://jira.adeo.no/browse/EY-1738 til deg 😃

**Review by madsop-nav — APPROVED** [review]

**Review by Watercolours — APPROVED** [review]
Fungerer finfint 👌

**Pull request merged**
